# Generated by Django 4.0.3 on 2022-05-09 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_article_aurhor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='aurhor',
            new_name='author',
        ),
    ]
