# Generated by Django 4.0.3 on 2022-05-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_author_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='article',
            field=models.ManyToManyField(blank=True, related_name='article', to='authentication.article'),
        ),
    ]
