# Generated by Django 4.0.3 on 2022-05-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_remove_conference_article_confarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='article',
            field=models.ManyToManyField(blank=True, related_name='article', to='authentication.article'),
        ),
        migrations.DeleteModel(
            name='ConfArticle',
        ),
    ]
