# Generated by Django 4.0.3 on 2022-04-28 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('acronym', models.CharField(max_length=500)),
                ('webpage', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=500)),
                ('startdate', models.DateField()),
                ('registrationdeadline', models.DateField()),
                ('soumissiondeadline', models.DateField()),
                ('primaryresearch', models.CharField(max_length=500)),
                ('secoundaryresearch', models.CharField(max_length=500)),
                ('areanite', models.CharField(max_length=500)),
                ('topicone', models.CharField(max_length=500)),
                ('topictwo', models.CharField(max_length=500)),
                ('topicthree', models.CharField(max_length=500)),
                ('topicfour', models.CharField(max_length=500)),
                ('pdftem', models.FileField(default='', upload_to='documents/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.AddConstraint(
            model_name='conference',
            constraint=models.UniqueConstraint(fields=('user',), name='name of constraint'),
        ),
    ]
