# Generated by Django 4.0.3 on 2022-04-29 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_conference_delete_account_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='conference',
            name='name of constraint',
        ),
    ]
