# Generated by Django 4.0.3 on 2022-05-08 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_chaiman'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('abstract', models.TextField(max_length=1000)),
                ('soumission_date', models.DateTimeField(auto_now_add=True)),
                ('domaine', models.CharField(max_length=100)),
                ('sous_domaine', models.CharField(max_length=100)),
                ('keywords', models.TextField(max_length=100)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=25)),
                ('organization', models.CharField(max_length=255)),
                ('webpage', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Confid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.conference')),
                ('articleid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='aurhor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.author'),
        ),
    ]
