# Generated by Django 4.0.3 on 2022-05-08 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_article_author_association_article_aurhor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='soumission_date',
            field=models.DateField(),
        ),
    ]
