# Generated by Django 4.0.3 on 2022-05-09 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_article_aurhor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='soumission_date',
        ),
    ]
