# Generated by Django 4.0.3 on 2022-05-09 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_remove_conference_article_conference_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='article',
        ),
        migrations.CreateModel(
            name='ConfArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Conference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.conference')),
                ('article', models.ManyToManyField(null=True, related_name='article', to='authentication.article')),
            ],
        ),
    ]
