# Generated by Django 4.0.3 on 2022-05-10 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_conference_reviewerone_conference_reviewerthree_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaiman',
            name='conf',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conference', to='authentication.conference'),
        ),
    ]
