# Generated by Django 4.0.3 on 2022-05-10 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_alter_chaiman_conf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conference',
            name='reviewerOne',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='reviewerThree',
        ),
        migrations.RemoveField(
            model_name='conference',
            name='reviewerTwo',
        ),
        migrations.AlterField(
            model_name='chaiman',
            name='conf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.conference'),
        ),
    ]
