# Generated by Django 4.0.3 on 2022-05-10 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0020_remove_conference_reviewerone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chairman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Chairmen',
            },
        ),
        migrations.AddField(
            model_name='conference',
            name='reviewerOne',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewerOne', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conference',
            name='reviewerThree',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewerThree', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='conference',
            name='reviewerTwo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewerTwo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Chaiman',
        ),
        migrations.AddField(
            model_name='chairman',
            name='conference',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conference', to='authentication.conference'),
        ),
        migrations.AddField(
            model_name='chairman',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
