# Generated by Django 4.0.3 on 2022-05-11 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0022_reviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='association',
            name='Confid',
        ),
        migrations.AddField(
            model_name='association',
            name='Confid',
            field=models.ManyToManyField(to='authentication.conference'),
        ),
        migrations.RemoveField(
            model_name='association',
            name='articleid',
        ),
        migrations.AddField(
            model_name='association',
            name='articleid',
            field=models.ManyToManyField(to='authentication.article'),
        ),
    ]
