# Generated by Django 4.0.3 on 2022-05-12 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_remove_association_confid_association_confid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='association',
        ),
    ]
