# Generated by Django 4.0.3 on 2022-05-14 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0026_alter_affectation_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.reviewer'),
        ),
    ]
