# Generated by Django 4.0.3 on 2022-05-15 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_alter_affectation_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='affectation',
            name='conferencee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.conference'),
            preserve_default=False,
        ),
    ]
