# Generated by Django 4.0.3 on 2022-05-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_affectation_conferencee'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviewing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('globalorig', models.CharField(max_length=500)),
                ('originality', models.CharField(max_length=500)),
                ('soundness', models.CharField(max_length=500)),
                ('presentation', models.CharField(max_length=500)),
                ('relevence', models.CharField(max_length=500)),
                ('importance', models.CharField(max_length=500)),
                ('observation', models.CharField(max_length=500)),
                ('finall', models.CharField(choices=[('SA', 'Strong Accept'), ('A', 'Accept'), ('B', 'Borderline'), ('W', 'Weak'), ('R', 'Reject')], max_length=500)),
            ],
        ),
    ]
