# Generated by Django 4.0.3 on 2022-05-22 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_reviewing'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewing',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewing',
            name='conferencee',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='authentication.conference'),
            preserve_default=False,
        ),
    ]
