# Generated by Django 4.0.3 on 2022-05-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0030_reviewing_article_reviewing_conferencee'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='reviewed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
