# Generated by Django 4.0.3 on 2022-05-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_article_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='reviewed',
        ),
    ]
