# Generated by Django 4.0.3 on 2022-05-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_remove_article_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewing',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
    ]
