# Generated by Django 4.0.3 on 2022-05-23 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_reviewing_reviewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewing',
            name='reviewed',
        ),
        migrations.CreateModel(
            name='aboutrev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observationn', models.CharField(max_length=500)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.article')),
                ('conferencee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.conference')),
            ],
        ),
    ]
