# Generated by Django 4.0.3 on 2022-05-23 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0034_remove_reviewing_reviewed_aboutrev'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutrev',
            name='reviewingg',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='authentication.reviewing'),
            preserve_default=False,
        ),
    ]
