# Generated by Django 4.0.3 on 2022-05-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0035_aboutrev_reviewingg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutrev',
            name='observationn',
            field=models.CharField(choices=[('You have been selected!!!', 'You have been selected'), ('You are not selected!!!', 'You are not selected ')], max_length=500),
        ),
        migrations.AlterField(
            model_name='conference',
            name='article',
            field=models.ManyToManyField(blank=True, related_name='conferences', to='authentication.article'),
        ),
        migrations.AlterField(
            model_name='reviewing',
            name='finall',
            field=models.CharField(choices=[('STRONG ACCEPT!', 'Strong Accept'), ('ACCEPT', 'Accept'), ('BORDERLINE', 'Borderline'), ('WEAK', 'Weak'), ('REJECT', 'Reject')], max_length=500),
        ),
    ]
