# Generated by Django 4.0.3 on 2022-06-18 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authentication', '0036_alter_aboutrev_observationn_alter_conference_article_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectation',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
